# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cod', models.CharField(max_length=5)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
    ]
