# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_companies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
