# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 01:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z\\s\\w]+$', b'Only alphanumeric characters are allowed.')]),
        ),
    ]
